language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

script: phpunit

matrix:
    include:
        - php: 7.0
        - php: 7.1
    fast_finish: true
